### ISSUE TITLE
Sample in README can cause error

### ISSUE THREAD

**Issue by niallthomson** [bcomnes/npm-bump#20]
Just thought I'd leave you a note that the sample in your `README` can easily cause issues since it uses `npm i`. I tried to use the action with my project and it took me a while troubleshooting `Git working directory not clean` errors to realize my `package-lock.json` was getting changed.

You should probably change that sample to use `npm ci`?

I likely struggled with this more because I'm not experienced with npm etc.

**Comment by bcomnes** [comment]
Typically with modules I add package-lock.json to the .gitignore since they do not get published to npm, and keeping them around can lead to a false sense of security. 

When your users install your module (with or without a package-lock.json), their install will effectively work as if there is no lock file (or merged with an existing one on their end). Meaning, if the module maintains and tests with a lock file, the set of transient dependencies used to test/release can often begin to diverge from what transients a fresh install would get, unless you are regenerating it on a daily cron or something. So tldr; module installs are always non-deterministic the first time. Kind of a crazy property of npm.

In my experience, defaulting to running tests against the no-lockfile scenario for modules tends to lead to more correct test results and publishes with less moving parts than maintaining a lock file along side a module. sindresorhus wrote a good article on this but I can't find it right now. This is why the example is that way.


All that said, if you want to maintain a package-lock.json in your release process, and you want it to get updated during the release (e.g. committed), simply stage any build files in your npm  `version` lifecycle step:

```
"version": "auto-changelog -p --template keepachangelog auto-changelog --breaking-pattern 'BREAKING CHANGE:' && git add CHANGELOG.md package-lock.json"
```

Or like you said, use `npm ci`.  I'll add a note to the readme.

**Comment by bcomnes** [comment]
Setting a reminder to follow up on a README improvement when I'm done moving next week.

**Comment by bcomnes** [comment]
Added something but lmk if you have any other ideas to improve it.
